

CREATE TABLE attendance_log (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  emp_id varchar(30) NOT NULL,
  shift_id varchar(30) DEFAULT NULL,
  branch_id varchar(30) NOT NULL,
  device_id varchar(30) NOT NULL,
  attendance_type varchar(20) NOT NULL COMMENT 'IN, OUT, BREAK_IN, BREAK_OUT',
  attendance_source varchar(20) DEFAULT 'DEVICE' COMMENT 'DEVICE, MOBILE_APP, MANUAL, WEB',
  verify_mode int(11) DEFAULT 0 COMMENT '1:Finger, 2:Face, 3:Card, 4:Password',
  verify_label varchar(50) DEFAULT NULL,
  log_date date NOT NULL,
  log_time time NOT NULL,
  geo_lat decimal(10,6) DEFAULT NULL,
  geo_lng decimal(10,6) DEFAULT NULL,
  geo_address varchar(255) DEFAULT NULL,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'SUBMITTED',
  approved_on datetime DEFAULT NULL,
  approved_by varchar(30) DEFAULT NULL COMMENT 'HR or manager who approves manual entries or exceptions',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Raw attendance logs captured from devices, mobile app, or manual entries';

CREATE TABLE branches (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  branch_id varchar(30) NOT NULL,
  branch_name varchar(100) NOT NULL,
  branch_address varchar(255) NOT NULL,
  mobile varchar(20) NOT NULL,
  email varchar(100) NOT NULL,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Company branches or locations';

CREATE TABLE companies (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  company_name varchar(255) NOT NULL COMMENT 'display name',
  legal_name varchar(255) DEFAULT NULL COMMENT 'Legal registered name',
  email varchar(150) DEFAULT NULL COMMENT 'Primary email',
  phone varchar(20) DEFAULT NULL COMMENT 'Phone number',
  website varchar(150) DEFAULT NULL COMMENT 'Website',
  address_line1 text DEFAULT NULL COMMENT 'Address line 1',
  address_line2 text DEFAULT NULL COMMENT 'Address line 2',
  city varchar(100) DEFAULT NULL COMMENT 'City',
  state varchar(100) DEFAULT NULL COMMENT 'State',
  country varchar(100) DEFAULT NULL COMMENT 'Country',
  postal_code varchar(20) DEFAULT NULL COMMENT 'Postal code',
  timezone varchar(50) DEFAULT 'UTC+06:00' COMMENT 'timezone',
  language_code varchar(10) DEFAULT NULL COMMENT 'Language code',
  fiscal_year_start_month tinyint(3) UNSIGNED NOT NULL DEFAULT 1 COMMENT '1=Jan, 7=July etc',
  favicon_url varchar(255) DEFAULT NULL COMMENT 'Company favicon URL',
  logo_url varchar(255) DEFAULT NULL COMMENT 'Company logo URL',
  banner_url varchar(255) DEFAULT NULL COMMENT 'Company banner image URL',
  status_type varchar(20) DEFAULT 'ACTIVE',
  note text DEFAULT NULL,
  created_on timestamp NOT NULL DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Company information master table';

INSERT INTO companies (id, cid, company_name, legal_name, email, phone, website, address_line1, address_line2, city, state, country, postal_code, timezone, language_code, fiscal_year_start_month, favicon_url, logo_url, banner_url, status_type, note, created_on, created_by, updated_on, updated_by) VALUES
(1, 'AIBL', 'Al-Arafah Islami Bank', 'Al-Arafah Islami Bank PLC', 'info@al-arafahbank.com', '+880-2-9571144', 'https://www.al-arafahbank.com', '36, Dilkusha Commercial Area', 'Motijheel', 'Dhaka', 'Dhaka', 'Bangladesh', '1000', 'UTC+06:00', 'bn', 7, 'https://www.al-arafahbank.com/favicon.ico', 'https://www.al-arafahbank.com/logo.png', 'https://www.al-arafahbank.com/banner.png', 'ACTIVE', 'Al-Arafah Islami Bank Limited — one of the leading Islamic Shariah-based banks in Bangladesh, established in 1995.', '2026-06-03 06:44:23', 'SYSTEM', NULL, NULL);

CREATE TABLE company_settings (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL,
  s_group varchar(100) NOT NULL,
  s_key varchar(100) NOT NULL,
  s_value varchar(255) NOT NULL,
  note text DEFAULT NULL,
  status_type enum('active','inactive') DEFAULT 'active',
  created_on timestamp NOT NULL DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Per-company configuration overrides for HR policies, attendance rules, payroll, etc.';

CREATE TABLE departments (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  department_id varchar(30) NOT NULL,
  department_name varchar(100) NOT NULL,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Company departments or functional areas';

CREATE TABLE designations (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  designation_id varchar(30) NOT NULL,
  designation_name varchar(100) NOT NULL,
  depth int(11) DEFAULT 0 COMMENT '0=Top Level, 1=Subordinate',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Employee designations or roles';

CREATE TABLE devices (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  branch_id varchar(30) NOT NULL,
  device_id varchar(30) NOT NULL,
  device_type varchar(50) NOT NULL,
  device_name varchar(100) NOT NULL,
  device_model varchar(100) DEFAULT NULL COMMENT 'Model or version info (e.g., Anviz VF30 Pro)',
  firmware_version varchar(50) DEFAULT NULL COMMENT 'Firmware version for biometric devices',
  device_serial varchar(100) DEFAULT NULL COMMENT 'Serial number or unique identifier',
  device_mac varchar(50) DEFAULT NULL COMMENT 'MAC address for networked devices',
  ip_address varchar(20) NOT NULL,
  subnet_mask varchar(20) DEFAULT '255.255.255.0',
  gateway varchar(20) DEFAULT NULL,
  comm_port int(11) DEFAULT 5010 COMMENT 'Communication port number',
  admin_user_id varchar(50) NOT NULL,
  admin_password varchar(255) NOT NULL,
  device_token varchar(255) DEFAULT NULL COMMENT 'Secret token for API authentication/Push mode',
  comm_type varchar(20) DEFAULT 'TCP' COMMENT 'e.g., TCP, UDP, HTTP',
  comm_mode varchar(20) DEFAULT 'PUSH' COMMENT 'e.g., PUSH, PULL',
  sync_interval_sec int(11) DEFAULT 300 COMMENT 'Sync interval in seconds',
  last_synced_at timestamp NULL DEFAULT NULL,
  last_heartbeat_at timestamp NULL DEFAULT NULL COMMENT 'Timestamp of last ping from device',
  max_user_count int(11) DEFAULT 0,
  current_user_count int(11) DEFAULT 0,
  max_log_count int(11) DEFAULT 0,
  current_log_count int(11) DEFAULT 0,
  last_error_log text DEFAULT NULL COMMENT 'Stores the last connection or sync error message',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE' COMMENT 'ACTIVE, INACTIVE, MAINTENANCE, OFFLINE',
  created_on timestamp NOT NULL DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Branch-specific Biometric or attendance devices used for employee check-in/out';

CREATE TABLE device_commands (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  branch_id varchar(30) NOT NULL,
  device_id varchar(30) NOT NULL,
  command_text text NOT NULL,
  retry_count int(11) DEFAULT 0,
  response_text text DEFAULT NULL,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'PENDING',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  executed_on datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Commands queued for devices, e.g., to update firmware, sync data, or manage users';

CREATE TABLE employees (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  emp_id varchar(30) NOT NULL,
  emp_name varchar(50) NOT NULL,
  emp_password varchar(255) NOT NULL,
  card_number varchar(30) DEFAULT NULL COMMENT 'RFID/Proximity Card Number',
  emp_type varchar(20) DEFAULT 'PERMANENT',
  mobile varchar(20) NOT NULL,
  email varchar(100) NOT NULL,
  gender varchar(10) DEFAULT NULL,
  dob date DEFAULT NULL,
  join_date date NOT NULL,
  resign_date date DEFAULT NULL,
  photo_url varchar(255) DEFAULT NULL,
  nid_number varchar(30) DEFAULT NULL,
  is_login_allowed tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 = Can login to web/app, 0 = No login access',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Employee records with basic information';

CREATE TABLE employee_biometrics (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  emp_id varchar(30) NOT NULL,
  bio_type varchar(20) NOT NULL COMMENT 'e.g., FINGERPRINT, FACE, IRIS',
  bio_data longtext NOT NULL COMMENT ' Encoded biometric template data or JSON with metadata',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Employee biometric records';

CREATE TABLE employee_branches (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  emp_id varchar(30) NOT NULL,
  branch_id varchar(30) NOT NULL,
  effective_from date NOT NULL,
  effective_to date DEFAULT NULL,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Employee branch assignments';

CREATE TABLE employee_department (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  emp_id varchar(30) NOT NULL,
  department_id varchar(30) NOT NULL,
  effective_from date NOT NULL,
  effective_to date DEFAULT NULL,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Employee department assignments';

CREATE TABLE employee_designation (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  emp_id varchar(30) NOT NULL,
  designation_id varchar(30) NOT NULL,
  effective_from date NOT NULL,
  effective_to date DEFAULT NULL,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Employee designation assignments';

CREATE TABLE employee_devices (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  branch_id varchar(30) NOT NULL,
  device_id varchar(30) NOT NULL,
  emp_id varchar(30) NOT NULL,
  admin_level tinyint(3) UNSIGNED DEFAULT 0 COMMENT '0=Normal User, 1=Special Admin',
  effective_from date NOT NULL,
  effective_to date DEFAULT NULL,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Mapping of employees to specific devices for access control or admin privileges';

CREATE TABLE employee_shifts (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  emp_id varchar(30) NOT NULL,
  shift_id varchar(30) NOT NULL,
  effective_from date NOT NULL,
  effective_to date DEFAULT NULL COMMENT 'NULL means currently active shift',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Employee shift assignments';

CREATE TABLE holidays (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  holiday_id varchar(30) NOT NULL,
  holiday_name varchar(100) NOT NULL,
  holiday_type varchar(30) DEFAULT 'PUBLIC',
  effective_from date NOT NULL,
  effective_to date NOT NULL,
  scope_type varchar(20) DEFAULT 'GLOBAL' COMMENT 'GLOBAL = All branches closed, SPECIFIC = Handled via exceptions table',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='List of company holidays';

CREATE TABLE holiday_exceptions (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  holiday_id varchar(30) NOT NULL,
  branch_id varchar(30) NOT NULL,
  effective_from date NOT NULL,
  effective_to date NOT NULL COMMENT 'For single day exception, effective_from and effective_to will be same',
  exception_type varchar(20) DEFAULT 'FORCE_OPEN' COMMENT 'FORCE_OPEN = open during holiday, FORCE_CLOSE = closed during workday',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Exceptions to holiday rules for specific branches or days, e.g., branch open on a public holiday or closed on a regular workday';

CREATE TABLE modules (
  id int PRIMARY KEY AUTO_INCREMENT,
  module_id varchar(30) NOT NULL,
  module_name varchar(100) NOT NULL,
  module_group varchar(100) DEFAULT NULL COMMENT 'HR, Finance, Office, Security',
  icon varchar(100) DEFAULT NULL COMMENT 'Frontend icon name',
  is_clickable tinyint(1) DEFAULT 1 COMMENT 'Whether this module is clickable in the UI',
  route_path varchar(255) DEFAULT NULL COMMENT 'Only set when is_clickable=TRUE',
  display_order int(11) DEFAULT NULL COMMENT 'UI ordering',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Application modules or features for role-based access control';

INSERT INTO modules (id, module_id, module_name, module_group, icon, is_clickable, route_path, display_order, note, status_type, created_on, created_by, updated_on, updated_by) VALUES
(1, 'MOD_DASHBOARD', 'Dashboard', NULL, 'ti-dashboard', 1, '/dashboard', 1, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(2, 'MOD_HR_EMPLOYEE', 'Employee', 'HR', 'ti-users', 0, NULL, 1, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(3, 'MOD_HR_DEPT', 'Department', 'HR', 'ti-building', 1, '/hr/department', 2, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(4, 'MOD_HR_DESIG', 'Designation', 'HR', 'ti-award', 1, '/hr/designation', 3, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(5, 'MOD_HR_BRANCH', 'Branch', 'HR', 'ti-map-pin', 1, '/hr/branch', 4, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(6, 'MOD_ATT_ATTENDANCE', 'Attendance', 'Attendance', 'ti-clock', 0, NULL, 1, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(7, 'MOD_ATT_SHIFT', 'Shift', 'Attendance', 'ti-calendar-time', 1, '/attendance/shift', 2, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(8, 'MOD_ATT_DEVICE', 'Device', 'Attendance', 'ti-device-desktop', 1, '/attendance/device', 3, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(9, 'MOD_PAY_PAYROLL', 'Payroll', 'Payroll', 'ti-cash', 0, NULL, 1, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(10, 'MOD_LVE_LEAVE', 'Leave', 'Leave', 'ti-calendar-off', 0, NULL, 1, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(11, 'MOD_SET_SETTINGS', 'Settings', 'Settings', 'ti-settings', 0, NULL, 1, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(12, 'MOD_SET_HOLIDAY', 'Holiday', 'Settings', 'ti-beach', 1, '/settings/holiday', 2, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(13, 'MOD_SET_WEEKEND', 'Weekend Policy', 'Settings', 'ti-calendar-week', 1, '/settings/weekend', 3, NULL, 'ACTIVE', '2026-06-03 12:33:57', NULL, NULL, NULL),
(14, 'MOD_SET_COMPANY', 'Company', 'Settings', 'ti-building-skyscraper', 1, '/settings/company', 4, NULL, 'ACTIVE', '2026-06-03 12:36:36', NULL, NULL, NULL);

CREATE TABLE roles (
  id int PRIMARY KEY AUTO_INCREMENT,
  role_id varchar(30) NOT NULL,
  role_name varchar(100) NOT NULL,
  role_type enum('SYSTEM','COMPANY') NOT NULL COMMENT 'SYSTEM = global role, COMPANY = company-specific role',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='User roles and their associated permissions';

INSERT INTO roles (id, role_id, role_name, role_type, note, status_type, created_on, created_by, updated_on, updated_by) VALUES
(1, 'ROLE_SUPER_ADMIN', 'Super Admin', 'SYSTEM', 'Full access to everything', 'ACTIVE', '2026-06-03 12:35:14', NULL, NULL, NULL),
(2, 'ROLE_SYS_MANAGER', 'System Manager', 'SYSTEM', 'Manages system-level settings', 'ACTIVE', '2026-06-03 12:35:14', NULL, NULL, NULL),
(3, 'ROLE_HR_MANAGER', 'HR Manager', 'COMPANY', 'Manages HR, employee, attendance', 'ACTIVE', '2026-06-03 12:35:14', NULL, NULL, NULL),
(4, 'ROLE_HR_OFFICER', 'HR Officer', 'COMPANY', 'Daily HR operations, limited access', 'ACTIVE', '2026-06-03 12:35:14', NULL, NULL, NULL),
(5, 'ROLE_ACCOUNTS', 'Accounts Officer', 'COMPANY', 'Payroll and finance access only', 'ACTIVE', '2026-06-03 12:35:14', NULL, NULL, NULL),
(6, 'ROLE_BRANCH_MGR', 'Branch Manager', 'COMPANY', 'Branch-level attendance and employee view', 'ACTIVE', '2026-06-03 12:35:14', NULL, NULL, NULL),
(7, 'ROLE_EMPLOYEE', 'Employee', 'COMPANY', 'Self-service only — own attendance, leave', 'ACTIVE', '2026-06-03 12:35:14', NULL, NULL, NULL);

CREATE TABLE role_permissions (
  id int PRIMARY KEY AUTO_INCREMENT,
  role_id varchar(30) NOT NULL,
  module_id varchar(30) NOT NULL,
  sub_module_id varchar(30) NOT NULL DEFAULT '' COMMENT 'Empty string means permission applies to entire module',
  can_view tinyint(1) DEFAULT 0 COMMENT '1 = Sidebar menu visible',
  can_create tinyint(1) DEFAULT 0,
  can_edit tinyint(1) DEFAULT 0,
  can_delete tinyint(1) DEFAULT 0,
  can_export tinyint(1) DEFAULT 0,
  can_import tinyint(1) DEFAULT 0,
  can_approve tinyint(1) DEFAULT 0 COMMENT 'For workflows like leave, payroll approval',
  can_reject tinyint(1) DEFAULT 0 COMMENT 'For workflows like leave, payroll rejection',
  can_view_sensitive tinyint(1) DEFAULT 0 COMMENT 'Allows viewing sensitive data like salaries, NID, etc.',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Role-wise permission per module and sub-module';

INSERT INTO role_permissions (id, role_id, module_id, sub_module_id, can_view, can_create, can_edit, can_delete, can_export, can_import, can_approve, can_reject, can_view_sensitive, note, status_type, created_on, created_by, updated_on, updated_by) VALUES
(1, 'ROLE_SUPER_ADMIN', 'MOD_SET_COMPANY', '', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:20', NULL, NULL, NULL),
(2, 'ROLE_SUPER_ADMIN', 'MOD_DASHBOARD', '', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(3, 'ROLE_SUPER_ADMIN', 'MOD_HR_EMPLOYEE', 'SM_EMP_LIST', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(4, 'ROLE_SUPER_ADMIN', 'MOD_HR_EMPLOYEE', 'SM_EMP_ADD', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(5, 'ROLE_SUPER_ADMIN', 'MOD_HR_EMPLOYEE', 'SM_EMP_TRANSFER', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(6, 'ROLE_SUPER_ADMIN', 'MOD_HR_EMPLOYEE', 'SM_EMP_RESIGN', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(7, 'ROLE_SUPER_ADMIN', 'MOD_HR_EMPLOYEE', 'SM_EMP_DOCUMENT', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(8, 'ROLE_SUPER_ADMIN', 'MOD_HR_EMPLOYEE', 'SM_EMP_BIOMETRIC', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(9, 'ROLE_SUPER_ADMIN', 'MOD_HR_DEPT', '', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(10, 'ROLE_SUPER_ADMIN', 'MOD_HR_DESIG', '', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(11, 'ROLE_SUPER_ADMIN', 'MOD_HR_BRANCH', '', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(12, 'ROLE_SUPER_ADMIN', 'MOD_ATT_ATTENDANCE', 'SM_ATT_DAILY', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(13, 'ROLE_SUPER_ADMIN', 'MOD_ATT_ATTENDANCE', 'SM_ATT_MANUAL', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(14, 'ROLE_SUPER_ADMIN', 'MOD_ATT_ATTENDANCE', 'SM_ATT_REPORT', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(15, 'ROLE_SUPER_ADMIN', 'MOD_ATT_ATTENDANCE', 'SM_ATT_SUMMARY', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(16, 'ROLE_SUPER_ADMIN', 'MOD_ATT_SHIFT', '', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(17, 'ROLE_SUPER_ADMIN', 'MOD_ATT_DEVICE', '', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(18, 'ROLE_SUPER_ADMIN', 'MOD_PAY_PAYROLL', 'SM_PAY_SETUP', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(19, 'ROLE_SUPER_ADMIN', 'MOD_PAY_PAYROLL', 'SM_PAY_SHEET', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(20, 'ROLE_SUPER_ADMIN', 'MOD_PAY_PAYROLL', 'SM_PAY_BONUS', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(21, 'ROLE_SUPER_ADMIN', 'MOD_PAY_PAYROLL', 'SM_PAY_DEDUCTION', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(22, 'ROLE_SUPER_ADMIN', 'MOD_PAY_PAYROLL', 'SM_PAY_REPORT', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(23, 'ROLE_SUPER_ADMIN', 'MOD_LVE_LEAVE', 'SM_LVE_POLICY', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(24, 'ROLE_SUPER_ADMIN', 'MOD_LVE_LEAVE', 'SM_LVE_APPLY', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(25, 'ROLE_SUPER_ADMIN', 'MOD_LVE_LEAVE', 'SM_LVE_APPROVAL', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(26, 'ROLE_SUPER_ADMIN', 'MOD_LVE_LEAVE', 'SM_LVE_BALANCE', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(27, 'ROLE_SUPER_ADMIN', 'MOD_LVE_LEAVE', 'SM_LVE_REPORT', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(28, 'ROLE_SUPER_ADMIN', 'MOD_SET_SETTINGS', 'SM_SET_ROLES', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(29, 'ROLE_SUPER_ADMIN', 'MOD_SET_SETTINGS', 'SM_SET_USERS', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(30, 'ROLE_SUPER_ADMIN', 'MOD_SET_SETTINGS', 'SM_SET_COMPANY', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(31, 'ROLE_SUPER_ADMIN', 'MOD_SET_HOLIDAY', '', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(32, 'ROLE_SUPER_ADMIN', 'MOD_SET_WEEKEND', '', 1, 1, 1, 1, 1, 1, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(33, 'ROLE_HR_MANAGER', 'MOD_DASHBOARD', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(34, 'ROLE_HR_MANAGER', 'MOD_HR_EMPLOYEE', 'SM_EMP_LIST', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(35, 'ROLE_HR_MANAGER', 'MOD_HR_EMPLOYEE', 'SM_EMP_ADD', 1, 1, 1, 0, 0, 1, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(36, 'ROLE_HR_MANAGER', 'MOD_HR_EMPLOYEE', 'SM_EMP_TRANSFER', 1, 1, 1, 0, 0, 0, 1, 1, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(37, 'ROLE_HR_MANAGER', 'MOD_HR_EMPLOYEE', 'SM_EMP_RESIGN', 1, 1, 1, 0, 0, 0, 1, 1, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(38, 'ROLE_HR_MANAGER', 'MOD_HR_EMPLOYEE', 'SM_EMP_DOCUMENT', 1, 1, 1, 1, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(39, 'ROLE_HR_MANAGER', 'MOD_HR_EMPLOYEE', 'SM_EMP_BIOMETRIC', 1, 1, 1, 1, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(40, 'ROLE_HR_MANAGER', 'MOD_HR_DEPT', '', 1, 1, 1, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(41, 'ROLE_HR_MANAGER', 'MOD_HR_DESIG', '', 1, 1, 1, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(42, 'ROLE_HR_MANAGER', 'MOD_HR_BRANCH', '', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(43, 'ROLE_HR_MANAGER', 'MOD_ATT_ATTENDANCE', 'SM_ATT_DAILY', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(44, 'ROLE_HR_MANAGER', 'MOD_ATT_ATTENDANCE', 'SM_ATT_MANUAL', 1, 1, 1, 0, 0, 0, 1, 1, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(45, 'ROLE_HR_MANAGER', 'MOD_ATT_ATTENDANCE', 'SM_ATT_REPORT', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(46, 'ROLE_HR_MANAGER', 'MOD_ATT_ATTENDANCE', 'SM_ATT_SUMMARY', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(47, 'ROLE_HR_MANAGER', 'MOD_ATT_SHIFT', '', 1, 1, 1, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(48, 'ROLE_HR_MANAGER', 'MOD_LVE_LEAVE', 'SM_LVE_POLICY', 1, 1, 1, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(49, 'ROLE_HR_MANAGER', 'MOD_LVE_LEAVE', 'SM_LVE_APPLY', 1, 1, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(50, 'ROLE_HR_MANAGER', 'MOD_LVE_LEAVE', 'SM_LVE_APPROVAL', 1, 0, 0, 0, 0, 0, 1, 1, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(51, 'ROLE_HR_MANAGER', 'MOD_LVE_LEAVE', 'SM_LVE_BALANCE', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(52, 'ROLE_HR_MANAGER', 'MOD_LVE_LEAVE', 'SM_LVE_REPORT', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(53, 'ROLE_HR_MANAGER', 'MOD_SET_HOLIDAY', '', 1, 1, 1, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(54, 'ROLE_HR_MANAGER', 'MOD_SET_WEEKEND', '', 1, 1, 1, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(55, 'ROLE_HR_OFFICER', 'MOD_DASHBOARD', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(56, 'ROLE_HR_OFFICER', 'MOD_HR_EMPLOYEE', 'SM_EMP_LIST', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(57, 'ROLE_HR_OFFICER', 'MOD_HR_EMPLOYEE', 'SM_EMP_ADD', 1, 1, 1, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(58, 'ROLE_HR_OFFICER', 'MOD_HR_EMPLOYEE', 'SM_EMP_DOCUMENT', 1, 1, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(59, 'ROLE_HR_OFFICER', 'MOD_ATT_ATTENDANCE', 'SM_ATT_DAILY', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(60, 'ROLE_HR_OFFICER', 'MOD_ATT_ATTENDANCE', 'SM_ATT_MANUAL', 1, 1, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(61, 'ROLE_HR_OFFICER', 'MOD_ATT_ATTENDANCE', 'SM_ATT_REPORT', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(62, 'ROLE_HR_OFFICER', 'MOD_LVE_LEAVE', 'SM_LVE_APPLY', 1, 1, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(63, 'ROLE_HR_OFFICER', 'MOD_LVE_LEAVE', 'SM_LVE_BALANCE', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(64, 'ROLE_ACCOUNTS', 'MOD_DASHBOARD', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(65, 'ROLE_ACCOUNTS', 'MOD_HR_EMPLOYEE', 'SM_EMP_LIST', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(66, 'ROLE_ACCOUNTS', 'MOD_PAY_PAYROLL', 'SM_PAY_SETUP', 1, 1, 1, 0, 0, 0, 0, 0, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(67, 'ROLE_ACCOUNTS', 'MOD_PAY_PAYROLL', 'SM_PAY_SHEET', 1, 1, 1, 0, 1, 0, 1, 1, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(68, 'ROLE_ACCOUNTS', 'MOD_PAY_PAYROLL', 'SM_PAY_BONUS', 1, 1, 1, 0, 1, 0, 0, 0, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(69, 'ROLE_ACCOUNTS', 'MOD_PAY_PAYROLL', 'SM_PAY_DEDUCTION', 1, 1, 1, 0, 1, 0, 0, 0, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(70, 'ROLE_ACCOUNTS', 'MOD_PAY_PAYROLL', 'SM_PAY_REPORT', 1, 0, 0, 0, 1, 0, 0, 0, 1, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(71, 'ROLE_ACCOUNTS', 'MOD_ATT_ATTENDANCE', 'SM_ATT_SUMMARY', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(72, 'ROLE_BRANCH_MGR', 'MOD_DASHBOARD', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(73, 'ROLE_BRANCH_MGR', 'MOD_HR_EMPLOYEE', 'SM_EMP_LIST', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(74, 'ROLE_BRANCH_MGR', 'MOD_ATT_ATTENDANCE', 'SM_ATT_DAILY', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(75, 'ROLE_BRANCH_MGR', 'MOD_ATT_ATTENDANCE', 'SM_ATT_REPORT', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(76, 'ROLE_BRANCH_MGR', 'MOD_ATT_ATTENDANCE', 'SM_ATT_SUMMARY', 1, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(77, 'ROLE_BRANCH_MGR', 'MOD_LVE_LEAVE', 'SM_LVE_APPROVAL', 1, 0, 0, 0, 0, 0, 1, 1, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(78, 'ROLE_EMPLOYEE', 'MOD_DASHBOARD', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(79, 'ROLE_EMPLOYEE', 'MOD_ATT_ATTENDANCE', 'SM_ATT_DAILY', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(80, 'ROLE_EMPLOYEE', 'MOD_LVE_LEAVE', 'SM_LVE_APPLY', 1, 1, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL),
(81, 'ROLE_EMPLOYEE', 'MOD_LVE_LEAVE', 'SM_LVE_BALANCE', 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 'ACTIVE', '2026-06-03 12:37:35', NULL, NULL, NULL);

CREATE TABLE setting_keys (
  id int PRIMARY KEY AUTO_INCREMENT,
  scope_type enum('SYSTEM','COMPANY') NOT NULL COMMENT 'SYSTEM = global settings, COMPANY = per-company configurable',
  s_group varchar(100) NOT NULL,
  s_key varchar(100) NOT NULL,
  s_label varchar(150) NOT NULL,
  input_type enum('text','number','boolean','select','date','time','datetime','textarea') NOT NULL DEFAULT 'text',
  default_value varchar(255) NOT NULL DEFAULT '' COMMENT 'Fallback value if not set in system/company settings',
  max_length int(10) UNSIGNED DEFAULT NULL COMMENT 'Max character length for text/textarea input. NULL = no limit',
  is_editable tinyint(1) NOT NULL DEFAULT 1 COMMENT '0 = Read-only in UI e.g., app_version',
  status_type varchar(20) DEFAULT 'ACTIVE',
  note text DEFAULT NULL,
  created_on timestamp NOT NULL DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Registry of all configurable setting keys for both system and company scopes';

INSERT INTO setting_keys (id, scope_type, s_group, s_key, s_label, input_type, default_value, max_length, is_editable, status_type, note, created_on, created_by, updated_on, updated_by) VALUES
(1, 'SYSTEM', 'AUTH', 'allow_public_signup', 'Allow Public Signup', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(2, 'SYSTEM', 'AUTH', 'signup_requires_approval', 'Signup Requires Approval', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(3, 'SYSTEM', 'AUTH', 'allow_remember_me', 'Allow Remember Me', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(4, 'SYSTEM', 'AUTH', 'remember_me_days', 'Remember Me Duration (Days)', 'number', '30', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(5, 'SYSTEM', 'AUTH', 'allow_forgot_password', 'Allow Forgot Password', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(6, 'SYSTEM', 'AUTH', 'forgot_password_link_expiry_minutes', 'Forgot Password Link Expiry (Min)', 'number', '30', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(7, 'SYSTEM', 'AUTH', 'max_login_attempts', 'Max Login Attempts', 'number', '5', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(8, 'SYSTEM', 'AUTH', 'login_lockout_minutes', 'Lockout Duration (Minutes)', 'number', '15', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(9, 'SYSTEM', 'AUTH', 'session_timeout_minutes', 'Session Timeout (Minutes)', 'number', '60', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(10, 'SYSTEM', 'AUTH', 'otp_expiry_minutes', 'OTP Expiry (Minutes)', 'number', '5', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(11, 'SYSTEM', 'AUTH', 'max_otp_attempts', 'Max OTP Attempts', 'number', '3', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(12, 'SYSTEM', 'SECURITY', 'password_min_length', 'Min Password Length', 'number', '8', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(13, 'SYSTEM', 'SECURITY', 'password_expiry_days', 'Password Expiry (Days)', 'number', '90', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(14, 'SYSTEM', 'SECURITY', 'password_complexity_enabled', 'Enforce Password Complexity', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(15, 'SYSTEM', 'SECURITY', 'force_2fa_system_users', 'Force 2FA for System Users', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(16, 'SYSTEM', 'SECURITY', 'force_2fa_company_users', 'Force 2FA for Company Users', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(17, 'SYSTEM', 'SECURITY', 'ip_whitelist_enabled', 'Enable IP Whitelist', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(18, 'SYSTEM', 'SECURITY', 'allowed_ips', 'Allowed IP Addresses', 'textarea', '', 500, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(19, 'SYSTEM', 'SYSTEM', 'maintenance_mode', 'Maintenance Mode', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(20, 'SYSTEM', 'SYSTEM', 'maintenance_message', 'Maintenance Message', 'textarea', 'The system is currently under maintenance. Please try again later.', 500, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(21, 'SYSTEM', 'SYSTEM', 'app_version', 'App Version', 'text', '1.0.0', 20, 0, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(22, 'SYSTEM', 'SYSTEM', 'audit_log_retention_days', 'Audit Log Retention (Days)', 'number', '180', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(23, 'SYSTEM', 'LOCALIZATION', 'default_language', 'Default Language', 'select', 'en', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(24, 'SYSTEM', 'LOCALIZATION', 'default_timezone', 'Default Timezone', 'text', 'Asia/Dhaka', 50, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(25, 'SYSTEM', 'LOCALIZATION', 'default_date_format', 'Default Date Format', 'select', 'DD-MM-YYYY', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(26, 'SYSTEM', 'LOCALIZATION', 'default_time_format', 'Default Time Format', 'select', 'HH:mm', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(27, 'SYSTEM', 'FILE', 'max_upload_size_mb', 'Max Upload Size (MB)', 'number', '5', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(28, 'SYSTEM', 'FILE', 'allowed_file_extensions', 'Allowed File Extensions', 'textarea', 'jpg,jpeg,png,pdf,doc,docx,xlsx', 255, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(29, 'SYSTEM', 'FILE', 'storage_driver', 'Storage Driver', 'select', 'local', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(30, 'SYSTEM', 'FILE', 'storage_base_url', 'Storage Base URL', 'text', '', 255, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(31, 'SYSTEM', 'FILE', 'storage_bucket_name', 'Storage Bucket Name', 'text', '', 100, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(32, 'SYSTEM', 'BIOMETRIC_DEVICE', 'device_heartbeat_timeout_min', 'Heartbeat Timeout (Minutes)', 'number', '15', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(33, 'SYSTEM', 'BIOMETRIC_DEVICE', 'raw_log_retention_days', 'Raw Log Retention (Days)', 'number', '365', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(34, 'SYSTEM', 'BIOMETRIC_DEVICE', 'sync_retry_attempts', 'Sync Retry Attempts', 'number', '3', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(35, 'SYSTEM', 'BIOMETRIC_DEVICE', 'sync_retry_delay_seconds', 'Sync Retry Delay (Seconds)', 'number', '30', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(36, 'SYSTEM', 'BIOMETRIC_DEVICE', 'command_queue_timeout_minutes', 'Command Queue Timeout (Min)', 'number', '10', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(37, 'SYSTEM', 'BIOMETRIC_DEVICE', 'auto_mark_absent_enabled', 'Auto Mark Absent', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(38, 'SYSTEM', 'BIOMETRIC_DEVICE', 'auto_absent_run_time', 'Auto Absent Run Time', 'time', '23:30', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(39, 'COMPANY', 'AUTH', 'forgot_password_method', 'Forgot Password Method', 'select', 'EMAIL', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(40, 'COMPANY', 'AUTH', 'allow_remember_me', 'Allow Remember Me', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(41, 'COMPANY', 'SECURITY', 'force_2fa_users', 'Force 2FA for Users', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(42, 'COMPANY', 'SECURITY', 'two_fa_method', '2FA Method', 'select', 'EMAIL', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(43, 'COMPANY', 'SECURITY', 'ip_whitelist_enabled', 'Enable IP Whitelist', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(44, 'COMPANY', 'SECURITY', 'allowed_ips', 'Allowed IP Addresses', 'textarea', '', 500, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(45, 'COMPANY', 'SECURITY', 'password_complexity_enabled', 'Enforce Password Complexity', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(46, 'COMPANY', 'SECURITY', 'password_expiry_days', 'Password Expiry (Days)', 'number', '90', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(47, 'COMPANY', 'LOCALIZATION', 'language', 'Language', 'select', 'en', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(48, 'COMPANY', 'LOCALIZATION', 'timezone', 'Timezone', 'text', 'Asia/Dhaka', 50, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(49, 'COMPANY', 'LOCALIZATION', 'date_format', 'Date Format', 'select', 'DD-MM-YYYY', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(50, 'COMPANY', 'LOCALIZATION', 'time_format', 'Time Format', 'select', 'HH:mm', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(51, 'COMPANY', 'LOCALIZATION', 'currency_code', 'Currency Code', 'text', 'BDT', 10, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(52, 'COMPANY', 'LOCALIZATION', 'currency_symbol', 'Currency Symbol', 'text', '৳', 5, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(53, 'COMPANY', 'ATTENDANCE', 'auto_checkout_enabled', 'Auto Checkout', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(54, 'COMPANY', 'ATTENDANCE', 'auto_checkout_time', 'Auto Checkout Time', 'time', '23:59', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(55, 'COMPANY', 'ATTENDANCE', 'early_checkin_minutes', 'Early Check-in (Minutes)', 'number', '30', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(56, 'COMPANY', 'ATTENDANCE', 'late_mark_after_minutes', 'Late Mark After (Minutes)', 'number', '15', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(57, 'COMPANY', 'ATTENDANCE', 'half_day_threshold_hours', 'Half Day Threshold (Hours)', 'number', '4', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(58, 'COMPANY', 'ATTENDANCE', 'allow_manual_attendance', 'Allow Manual Attendance', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(59, 'COMPANY', 'ATTENDANCE', 'manual_attendance_approval', 'Manual Attendance Approval', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(60, 'COMPANY', 'ATTENDANCE', 'auto_absent_enabled', 'Auto Mark Absent', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(61, 'COMPANY', 'ATTENDANCE', 'auto_absent_run_time', 'Auto Absent Run Time', 'time', '23:30', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(62, 'COMPANY', 'LEAVE', 'leave_approval_levels', 'Leave Approval Levels', 'select', '1', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(63, 'COMPANY', 'LEAVE', 'allow_leave_in_probation', 'Allow Leave in Probation', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(64, 'COMPANY', 'LEAVE', 'max_consecutive_leave_days', 'Max Consecutive Leave Days', 'number', '15', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(65, 'COMPANY', 'LEAVE', 'allow_leave_encashment', 'Allow Leave Encashment', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(66, 'COMPANY', 'LEAVE', 'leave_carry_forward_enabled', 'Leave Carry Forward', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(67, 'COMPANY', 'LEAVE', 'max_carry_forward_days', 'Max Carry Forward Days', 'number', '0', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(68, 'COMPANY', 'PAYROLL', 'payroll_cycle', 'Payroll Cycle', 'select', 'MONTHLY', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(69, 'COMPANY', 'PAYROLL', 'pay_day', 'Pay Day', 'number', '25', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(70, 'COMPANY', 'PAYROLL', 'overtime_enabled', 'Enable Overtime', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(71, 'COMPANY', 'PAYROLL', 'overtime_rate_multiplier', 'Overtime Rate Multiplier', 'number', '1.5', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(72, 'COMPANY', 'PAYROLL', 'tax_enabled', 'Enable Tax Deduction', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(73, 'COMPANY', 'PAYROLL', 'provident_fund_enabled', 'Enable Provident Fund', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(74, 'COMPANY', 'PORTAL', 'employee_portal_enabled', 'Employee Portal', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(75, 'COMPANY', 'PORTAL', 'employee_can_view_payslip', 'View Payslip', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(76, 'COMPANY', 'PORTAL', 'employee_can_apply_leave', 'Apply Leave', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(77, 'COMPANY', 'PORTAL', 'employee_can_view_attendance', 'View Attendance', 'boolean', 'true', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL),
(78, 'COMPANY', 'PORTAL', 'employee_can_update_profile', 'Update Profile', 'boolean', 'false', NULL, 1, 'ACTIVE', NULL, '2026-06-10 04:26:56', 'SYSTEM', NULL, NULL);

CREATE TABLE shifts (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  shift_id varchar(30) NOT NULL,
  shift_name varchar(100) NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  grace_in int(11) DEFAULT 10 COMMENT 'Buffer time in minutes for late check-in',
  grace_out int(11) DEFAULT 10 COMMENT 'Buffer time in minutes for early check-out',
  break_minutes int(11) DEFAULT 60 COMMENT 'Unpaid break duration in minutes',
  work_hours decimal(4,2) NOT NULL COMMENT 'Target working hours, e.g., 8.00 or 9.00',
  is_night_shift tinyint(1) DEFAULT 0 COMMENT '1 = Shifts cross midnight (e.g., 10 PM to 6 AM)',
  is_short_shift tinyint(1) DEFAULT 0 COMMENT '1 = Half day or short shift (e.g., Saturday)',
  half_day_late_minutes int(11) DEFAULT 60 COMMENT 'After how many minutes employee is marked as Half-Day Late',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='List of available shifts';

CREATE TABLE sub_modules (
  id int PRIMARY KEY AUTO_INCREMENT,
  module_id varchar(30) NOT NULL COMMENT 'References modules.module_id',
  sub_module_id varchar(30) NOT NULL,
  sub_module_name varchar(100) NOT NULL,
  icon varchar(100) DEFAULT NULL COMMENT 'Menu specific icon',
  route_path varchar(255) DEFAULT NULL COMMENT 'Final URL for this specific module or feature',
  display_order int(11) DEFAULT 0,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Sub-modules or specific features within a module for more granular access control';

INSERT INTO sub_modules (id, module_id, sub_module_id, sub_module_name, icon, route_path, display_order, note, status_type, created_on, created_by, updated_on, updated_by) VALUES
(1, 'MOD_HR_EMPLOYEE', 'SM_EMP_LIST', 'Employee List', 'ti-list', '/hr/employee/list', 1, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(2, 'MOD_HR_EMPLOYEE', 'SM_EMP_ADD', 'Add Employee', 'ti-user-plus', '/hr/employee/add', 2, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(3, 'MOD_HR_EMPLOYEE', 'SM_EMP_TRANSFER', 'Transfer', 'ti-arrows-transfer', 'hr/employee/transfer', 3, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(4, 'MOD_HR_EMPLOYEE', 'SM_EMP_RESIGN', 'Resignation', 'ti-logout', '/hr/employee/resign', 4, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(5, 'MOD_HR_EMPLOYEE', 'SM_EMP_DOCUMENT', 'Documents', 'ti-file', '/hr/employee/document', 5, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(6, 'MOD_HR_EMPLOYEE', 'SM_EMP_BIOMETRIC', 'Biometric', 'ti-fingerprint', '/hr/employee/biometric', 6, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(7, 'MOD_ATT_ATTENDANCE', 'SM_ATT_DAILY', 'Daily Log', 'ti-calendar', '/attendance/daily', 1, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(8, 'MOD_ATT_ATTENDANCE', 'SM_ATT_MANUAL', 'Manual Entry', 'ti-pencil', '/attendance/manual', 2, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(9, 'MOD_ATT_ATTENDANCE', 'SM_ATT_REPORT', 'Attendance Report', 'ti-chart-bar', '/attendance/report', 3, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(10, 'MOD_ATT_ATTENDANCE', 'SM_ATT_SUMMARY', 'Monthly Summary', 'ti-table', '/attendance/summary', 4, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(11, 'MOD_PAY_PAYROLL', 'SM_PAY_SETUP', 'Salary Setup', 'ti-settings', '/payroll/setup', 1, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(12, 'MOD_PAY_PAYROLL', 'SM_PAY_SHEET', 'Salary Sheet', 'ti-file-invoice', '/payroll/sheet', 2, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(13, 'MOD_PAY_PAYROLL', 'SM_PAY_BONUS', 'Bonus', 'ti-gift', '/payroll/bonus', 3, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(14, 'MOD_PAY_PAYROLL', 'SM_PAY_DEDUCTION', 'Deduction', 'ti-minus', '/payroll/deduction', 4, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(15, 'MOD_PAY_PAYROLL', 'SM_PAY_REPORT', 'Payroll Report', 'ti-chart-bar', '/payroll/report', 5, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(16, 'MOD_LVE_LEAVE', 'SM_LVE_POLICY', 'Leave Policy', 'ti-settings', '/leave/policy', 1, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(17, 'MOD_LVE_LEAVE', 'SM_LVE_APPLY', 'Leave Apply', 'ti-send', '/leave/apply', 2, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(18, 'MOD_LVE_LEAVE', 'SM_LVE_APPROVAL', 'Leave Approval', 'ti-check', '/leave/approval', 3, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(19, 'MOD_LVE_LEAVE', 'SM_LVE_BALANCE', 'Leave Balance', 'ti-calculator', '/leave/balance', 4, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(20, 'MOD_LVE_LEAVE', 'SM_LVE_REPORT', 'Leave Report', 'ti-chart-bar', '/leave/report', 5, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(21, 'MOD_SET_SETTINGS', 'SM_SET_ROLES', 'Roles', 'ti-shield', '/settings/roles', 1, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(22, 'MOD_SET_SETTINGS', 'SM_SET_USERS', 'Users', 'ti-user-cog', '/settings/users', 2, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL),
(23, 'MOD_SET_SETTINGS', 'SM_SET_COMPANY', 'Company Profile', 'ti-building', '/settings/company', 3, NULL, 'ACTIVE', '2026-06-03 12:34:08', NULL, NULL, NULL);

CREATE TABLE system_settings (
  id bigint(20) NOT NULL,
  s_group varchar(100) NOT NULL,
  s_key varchar(100) NOT NULL,
  s_value varchar(255) NOT NULL,
  status_type enum('active','inactive') DEFAULT 'active',
  note text DEFAULT NULL,
  created_on timestamp NOT NULL DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Master / reference data and app settings values for dropdowns, config, and feature flags';

INSERT INTO system_settings (id, s_group, s_key, s_value, status_type, note, created_on, created_by, updated_on, updated_by) VALUES
(1, 'AUTH', 'allow_public_signup', 'false', 'active', 'Allow new companies to self-register from the public landing page', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(2, 'AUTH', 'signup_requires_approval', 'true', 'active', 'Newly registered company needs SYSTEM admin approval before activation', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(3, 'AUTH', 'allow_remember_me', 'true', 'active', 'Allow users to use Remember Me on login', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(4, 'AUTH', 'remember_me_days', '30', 'active', 'Token validity in days when Remember Me is checked', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(5, 'AUTH', 'allow_forgot_password', 'true', 'active', 'Allow users to reset password via forgot password flow', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(6, 'AUTH', 'max_login_attempts', '5', 'active', 'Failed login attempts allowed before account is locked', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(7, 'AUTH', 'login_lockout_minutes', '15', 'active', 'Duration in minutes an account stays locked after max failed attempts', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(8, 'AUTH', 'session_timeout_minutes', '60', 'active', 'Idle session auto-logout duration in minutes', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(9, 'AUTH', 'password_min_length', '8', 'active', 'Minimum character length required for passwords', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(10, 'AUTH', 'password_expiry_days', '90', 'active', 'Days before password must be changed. 0 = never expires', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(11, 'AUTH', 'otp_expiry_minutes', '5', 'active', 'OTP validity duration in minutes', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(12, 'AUTH', 'max_otp_attempts', '3', 'active', 'Max failed OTP attempts before lockout', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(13, 'SECURITY', 'force_2fa_system_users', 'true', 'active', 'Enforce mandatory 2FA for all SYSTEM type users', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(14, 'SECURITY', 'force_2fa_company_users', 'false', 'active', 'Enforce mandatory 2FA for all COMPANY type users', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(15, 'SECURITY', 'ip_whitelist_enabled', 'false', 'active', 'Restrict logins to whitelisted IP addresses only', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(16, 'SECURITY', 'allowed_ips', '', 'active', 'Comma-separated list of whitelisted IP addresses', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(17, 'SYSTEM', 'maintenance_mode', 'false', 'active', 'Put the entire application into maintenance mode', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(18, 'SYSTEM', 'maintenance_message', 'The system is currently under maintenance. Please try again later.', 'active', 'Message displayed to users during maintenance mode', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(19, 'LOCALIZATION', 'default_language', 'en', 'active', 'System-wide fallback language code (e.g., en, bn)', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(20, 'LOCALIZATION', 'default_timezone', 'Asia/Dhaka', 'active', 'System-wide fallback timezone identifier', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(21, 'LOCALIZATION', 'default_date_format', 'DD-MM-YYYY', 'active', 'Default date display format across the application', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(22, 'LOCALIZATION', 'default_time_format', 'HH:mm', 'active', '24-hour or 12-hour format. e.g., HH:mm or hh:mm A', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(23, 'FILE', 'max_upload_size_mb', '5', 'active', 'Maximum allowed file upload size in megabytes', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(24, 'FILE', 'allowed_file_extensions', 'jpg,jpeg,png,pdf,doc,docx,xlsx', 'active', 'Comma-separated list of permitted file upload extensions', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(25, 'FILE', 'storage_driver', 'local', 'active', 'Storage backend: local, s3, gcs', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(26, 'FILE', 'storage_base_url', '', 'active', 'Base URL for file access (required for s3/gcs)', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(27, 'FILE', 'storage_bucket_name', '', 'active', 'Bucket or container name (for s3/gcs)', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(28, 'BIOMETRIC_DEVICE', 'device_heartbeat_timeout_min', '15', 'active', 'Minutes after which a device is flagged OFFLINE if no heartbeat received', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(29, 'BIOMETRIC_DEVICE', 'raw_log_retention_days', '365', 'active', 'Days to retain raw attendance logs before archiving or purging', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(30, 'BIOMETRIC_DEVICE', 'sync_retry_attempts', '3', 'active', 'Number of retry attempts for a failed device sync', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(31, 'BIOMETRIC_DEVICE', 'sync_retry_delay_seconds', '30', 'active', 'Delay in seconds between sync retry attempts', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL),
(32, 'BIOMETRIC_DEVICE', 'command_queue_timeout_minutes', '10', 'active', 'Minutes before a pending device command is marked as FAILED', '2026-06-10 03:47:08', 'SYSTEM', NULL, NULL);

CREATE TABLE users (
  id int PRIMARY KEY AUTO_INCREMENT,
  user_id varchar(30) NOT NULL,
  user_type enum('SYSTEM','COMPANY') NOT NULL COMMENT 'SYSTEM = global user, COMPANY = company-level user',
  cid varchar(50) DEFAULT NULL COMMENT 'NULL for SYSTEM, required for COMPANY',
  user_name varchar(50) NOT NULL,
  user_pass varchar(255) NOT NULL,
  email varchar(100) NOT NULL,
  mobile varchar(20) NOT NULL,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='System users who can log in to the HRMS application';

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cid VARCHAR(50) DEFAULT NULL COMMENT 'NULL for SYSTEM, required for COMPANY',
  user_type ENUM('SYSTEM', 'COMPANY') NOT NULL COMMENT 'SYSTEM = global user, COMPANY = company-level user',
  user_id VARCHAR(30) NOT NULL,  
  user_name VARCHAR(50) NOT NULL,
  user_pass VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  profile_image VARCHAR(255) DEFAULT NULL,
  sync_code VARCHAR(50) DEFAULT NULL COMMENT 'Biometric/External Sync Code',
  sync_count INT DEFAULT 0 COMMENT 'Total sync iterations for mobile app or biometric device',
  fcm_token TEXT DEFAULT NULL COMMENT 'Push Notification Token for Mobile App',
  device_id VARCHAR(255) DEFAULT NULL COMMENT 'Bound Mobile Device ID for Security',
  last_login_on DATETIME DEFAULT NULL,
  last_login_ip VARCHAR(45) DEFAULT NULL,
  failed_login_attempts TINYINT DEFAULT 0,
  account_locked_until DATETIME DEFAULT NULL,
  note TEXT DEFAULT NULL,
  status_type VARCHAR(20) DEFAULT 'ACTIVE' COMMENT 'ACTIVE, INACTIVE, BLOCKED',
  created_on DATETIME DEFAULT CURRENT_TIMESTAMP(),
  created_by VARCHAR(50) DEFAULT NULL,
  updated_on DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(),
  updated_by VARCHAR(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='System users (Admins & Mobile Users) for HRMS';

INSERT INTO users (user_id, user_type, cid, user_name, user_pass, email, mobile, note, status_type, created_on, created_by, updated_on, updated_by) VALUES
('EON_SUPER_001', 'SYSTEM', NULL, 'superadmin', '1234', 'superadmin@hrms.system', '+8801700000000', 'Super Admin — full system access, manages all companies and system-level configurations.', 'ACTIVE', '2026-06-03 12:45:59', 'SYSTEM', '2026-06-21 16:13:31', NULL);

CREATE TABLE users_2fa_config (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) DEFAULT NULL COMMENT 'NULL for SYSTEM, required for COMPANY',
  user_id varchar(30) NOT NULL,
  two_fa_method enum('EMAIL','SMS','APP') DEFAULT 'EMAIL',
  two_fa_secret varchar(100) DEFAULT NULL COMMENT 'Used for Google/Microsoft Authenticator secret key',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Two-factor authentication configuration for users';

CREATE TABLE user_otps (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) DEFAULT NULL COMMENT 'NULL for SYSTEM, required for COMPANY',
  user_id varchar(30) NOT NULL,
  otp_type enum('LOGIN_2FA','PASSWORD_RESET','EMAIL_VERIFICATION') NOT NULL,
  otp_code varchar(10) NOT NULL,
  expires_on datetime NOT NULL,
  notes text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'PENDING',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Stores all short-lived OTP tokens for user authentication actions';

CREATE TABLE user_roles (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) DEFAULT NULL COMMENT 'NULL for SYSTEM, required for COMPANY',
  user_id varchar(30) NOT NULL,
  role_id varchar(30) NOT NULL,
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on datetime DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Mapping of users to their assigned roles for access control and permissions management';

INSERT INTO user_roles (id, cid, user_id, role_id, note, status_type, created_on, created_by, updated_on, updated_by) VALUES
(1, NULL, 'EON_SUPER_001', 'ROLE_SUPER_ADMIN', 'System-level super admin role assignment.', 'ACTIVE', '2026-06-03 12:46:06', 'SYSTEM', NULL, NULL);

CREATE TABLE weekend_policies (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  policy_id varchar(30) NOT NULL,
  policy_name varchar(100) NOT NULL COMMENT 'e.g., Standard Weekend, Roster Weekend',
  off_days varchar(50) NOT NULL COMMENT 'Comma separated integers or names. e.g., 4,5 for Fri,Sat',
  scope_type varchar(20) DEFAULT 'GLOBAL' COMMENT 'GLOBAL = Default for all branches, SPECIFIC = Handled via exceptions',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Weekend policies for each company';

CREATE TABLE weekend_policy_exceptions (
  id int PRIMARY KEY AUTO_INCREMENT,
  cid varchar(50) NOT NULL COMMENT 'Company reference',
  policy_id varchar(30) NOT NULL COMMENT 'References weekend_policies.policy_id',
  branch_id varchar(30) NOT NULL COMMENT 'The branch that has this specific weekend',
  note text DEFAULT NULL,
  status_type varchar(20) DEFAULT 'ACTIVE',
  created_on datetime DEFAULT current_timestamp(),
  created_by varchar(50) DEFAULT NULL,
  updated_on timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  updated_by varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Tracks branches that do not follow the global weekend policy';
